### ISSUE TITLE
Terms: "release"

### ISSUE THREAD

**Issue by sakimura** [oauthstuff/draft-selective-disclosure-jwt#10]
Using a single word "release" as a defined term is not a good practice. We will lose the capability to use "release" in the dictionary sense. You may say that it would be fine as we can capitalize it but it should be noted that the notion of capitalization does not exist in many languages and it will cause issues when translating. 

As the abbreviation indicates, perhaps it would be better to call it SD-JWT Release.

**Comment by Sakurann** [comment]
Agreed. SD-JWT-R or SD-JWT-Release would be better.

**Comment by danielfett** [comment]
I would be fine with that.

**Comment by Sakurann** [comment]
closing with PR #16
