### ISSUE TITLE
2. Terminology -- the way it is written does not look like Terms and definitions

### ISSUE THREAD

**Issue by sakimura** [oauthstuff/draft-selective-disclosure-jwt#11]
* The way it is written now does not look like terms and definitions. 
* It would also be a good practice to make it possible to the definition to replace the terms that appear in the main text. 
* With this respect, verbose explanations especially the mechanisms should be done in the "Concepts" section in the main text. In fact, much of the text in the current "terminology" mostly duplicates what is being explained in 3. Concept
* Also, examples etc. should be added as a note to the definition and not as part of the definition text. 

Proposes the following as amended text

**2. Terms and definitions**

**2.1 SD-JWT** 
signed JWT [[RFC7515](https://oauthstuff.github.io/draft-selective-disclosure-jwt/draft-fett-selective-disclosure-jwt-00.html#RFC7515)], that supports selective disclosure as defined in this document

Note to entry: Signed JWT is JWS. 

**2.2 release (SD-JWT-R)**
document that contains a subset of the claim values of an SD-JWT in a verifiable way

Note to entry: Holder binding is also possible. 

**2.3 issuer**
entity that create SD-JWTs (2.1)

**2.4 holder**
entity that has control over SD-JWTs (2.1) 

Note to entry: If holder binding is desired, the holder also has the signing key for the verification key contained in the SD-JWT.

**2.5 verifier** 
entity that checks and extracts the claims from SSD-JWT-R (2.2)

**Comment by Sakurann** [comment]
closing with PR #16
