### ISSUE TITLE
defining the SD-JWT claims family namespace

### ISSUE THREAD

**Issue by peppelinux** [oauthstuff/draft-selective-disclosure-jwt#111]
in this draft we found as well defined the claims `sd_digests` and `sd_release` and then the claim `hash_alg`.
If this hash_alg belongs only to SD-JWT it wound't be better to rename it `sd_hash_alg`?

**Comment by danielfett** [comment]
I would be fine with `sd_hash_alg`. It makes sense since the hash is used for the core functionality of the SD-JWT.

**Comment by peppelinux** [comment]
Me or someone of us on a PR for this?
@Sakurann your comments are important

**Comment by Sakurann** [comment]
I am ok with `sd_hash_alg`, though it is already only present in SD-JWT.

**Comment by peppelinux** [comment]
Ok, if you agree we may merge https://github.com/oauthstuff/draft-selective-disclosure-jwt/pull/115 and then https://github.com/oauthstuff/draft-selective-disclosure-jwt/pull/117 and a PR with this change will follow
