### ISSUE TITLE
Change title to 'Selective Disclosure for JWT'

### ISSUE THREAD

**Issue by danielfett** [oauthstuff/draft-selective-disclosure-jwt#125]
> It's subtle but this isn't exactly a type of JWT and the title 'Selective Disclosure JWT' is potentially misleading. The document is more defining some structures/claims for use in JWT that can (help) accomplish selective disclosure.  'Selective Disclosure with JWT' or 'Selective Disclosure for JWT' might be more appropriate.

_Originally posted by @bc-pi in https://github.com/oauthstuff/draft-selective-disclosure-jwt/issues/60#issuecomment-1167782800_

I have come across this also while preparing the presentation for IETF. I think 'Selective Disclosure for JWT' would make more sense than the current title.

**Comment by bc-pi** [comment]
Concur (obviously).
