### ISSUE TITLE
Clarify SD-JWT and SVC is different

### ISSUE THREAD

**Issue by Sakurann** [oauthstuff/draft-selective-disclosure-jwt#133]
Received feedback from Vittorio that this text is confusing: "The structure of sd_release object in the SD-JWT-R is the same as in SD-JWT" - whether SD-JWT and SVC are different objects or are different. Need to paraphrase/clarify

**Comment by peppelinux** [comment]
yes, when we moved from `sd` to `sd_release` we probably introduced this kind of typo.

**Comment by vibronet** [comment]
New release didn't fix it tho :)
