### ISSUE TITLE
No need for the wallet-generated hashes

### ISSUE THREAD

**Issue by Sakurann** [oauthstuff/draft-selective-disclosure-jwt#14]
In the security considerations section, add a recommendation to use uuidv4 or something that's standardised to generate salt

Based on @AlenHorvat 's comment on the PR https://github.com/oauthstuff/draft-selective-disclosure-jwt/pull/1#discussion_r877161631

**Comment by danielfett** [comment]
What is the advantage of using a UUID? Using a UUID wastes space by making the representation much longer. 

PKCE for example did not choose to use a UUID.

**Comment by alenhorvat** [comment]
Idea is to suggest something standardised for the salt generation to avoid misusing random number generators (const. seeds, timestamp as a seed, ...). I don't have a particular preference on what approach is recommended.

**Comment by danielfett** [comment]
Makes sense, but I don't think a UUID is a good fit here.

**Comment by danielfett** [comment]
RFC7636 (PKCE) says this in the security considerations:

> [7.1](https://datatracker.ietf.org/doc/html/rfc7636#section-7.1).  Entropy of the code_verifier
>
>   The security model relies on the fact that the code verifier is not
>   learned or guessed by the attacker.  It is vitally important to
>   adhere to this principle.  As such, the code verifier has to be
>   created in such a manner that it is cryptographically random and has
>   high entropy that it is not practical for the attacker to guess.

**Comment by alenhorvat** [comment]
> Makes sense, but I don't think a UUID is a good fit here.

I agree.
Should we make a recommendation or we just re-use the security consideration from PKCE without suggesting anything? 
From a standardisation point of view security consideration as above is sufficient (devs usually ask for a recommendation)
If this is the case, we can close the issue.

**Comment by danielfett** [comment]
I think we should be fine with the security recommendation.

**Comment by christianpaquin** [comment]
We should stay away from uuid for the salt, IMO. Many UID library do not generate cryptographically random values, as it is needed here.

**Comment by selfissued** [comment]
I agree that the current Security Considerations are sufficient.  I also agree that UUIDs have multiple problems.

I recommend that we close this issue with no further actions on this basis.

**Comment by Sakurann** [comment]
agree with the discussion. I did a PR #38 because I did not think the current security considerations reflected this conversation sufficiently well-enough.
