### ISSUE TITLE
Pls responed for this-How to include this in example simple 

### ISSUE THREAD

**Issue by Muthurajj** [oauthstuff/draft-selective-disclosure-jwt#140]
"vc": {
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
      "https://www.w3.org/2018/credentials/examples/v1"
    ],
    "type": [
      "VerifiableCredential",
      "UniversityDegreeCredential"
    ],

**Comment by danielfett** [comment]
See Issue #142.
