### ISSUE TITLE
VC generation in sd-jwt

### ISSUE THREAD

**Issue by Muthurajj** [oauthstuff/draft-selective-disclosure-jwt#143]
1.Can we generate VC using SD-JWT?

2.What is the verification_process and sub that you have mentioned in example yml file

3.If we can generate VC what should we change?

4.How to generate context and type like you have mentioned in document example 4?
5.Openid connect include in this library?

**Comment by danielfett** [comment]
1: See Issue #142 
2: See the eKYC spec for the verification_process, but the value here is only an example
3/4: The aim of the current python code is not to generate VCs, but to generate (more general) SD-JWTs.
5: I don't understand this question.
