### ISSUE TITLE
Location of "Challenge of Canonicalization Section"

### ISSUE THREAD

**Issue by Sakurann** [oauthstuff/draft-selective-disclosure-jwt#175]
Suggest we move this section lower, as with the new encoding approach I anticipate less questions regarding canonicalization, while this is a good clarification.

https://github.com/oauth-wg/oauth-selective-disclosure-jwt/pull/174/files#r1028969018

**Comment by bc-pi** [comment]
I recently had a conversation with a guy (editor of RFC7520 FWIW) who had some comments/observations that would support the idea of moving it into an appendix.

"my opinion: the entire discussion about canonicalization only serves to distract.  This document should only ever talk about the source hardening; if you really want/need to talk about c14n, put it in an appendix at the end" and "then that entire Section 5.1 ought to just be dropped then, I think"

**Comment by Sakurann** [comment]
ok, let's move to appendix
