### ISSUE TITLE
usage of sub_jwk

### ISSUE THREAD

**Issue by Sakurann** [oauthstuff/draft-selective-disclosure-jwt#23]
A comment from @b---c that I completely agree with.
> sub_jwk has a pretty narrow definition and corresponding registration from OIDC https://openid.net/specs/openid-connect-core-1_0.html#SelfIssuedResponse which seems a little different than how sd-jwt is maybe using it. If sub_jwk continues to be used, there might need to be some more explanation and maybe an update to the registry. Maybe.

**Comment by selfissued** [comment]
Also note this text in-00:
> Note: need to define how holder public key is included, right now examples are using sub_jwk I think.
There is currently no normative text in the spec saying how `sub_jwk` is used.

I do think that continuing to use the `sub_jwk` claim is fine.

**Comment by Sakurann** [comment]
per chat in Signal, I think it should be a URI (jwk-thumbprint-uri for sub_jwk, but can also be a DID). but as discussed in the chat, depends whether we think this is a layering violation and decide to not define holder binding in the spec...

**Comment by danielfett** [comment]
I see `sub_jwk` as part of an example here, not normative for the spec. See also my comment on issue #24.

**Comment by selfissued** [comment]
We do need to normatively say what claim we're using for the contained key.  Using `sub_jwk` seems like the obvious choice.

**Comment by Sakurann** [comment]
specifying `sub_jwk` normatively is somewhat contradictory to your comments on layering violation in Issue #24... I think we should say `sub_jwk` can be used but it is up to the implementors to decide what to use.
