### ISSUE TITLE
same key name `_sd` in SD-JWT and SVC

### ISSUE THREAD

**Issue by Sakurann** [oauthstuff/draft-selective-disclosure-jwt#25]
A comment from @b---c
> I'd think the SVC should use a different key name than "_sd". I find it confusing that the same key name is used for the selectively disclosable claims and the salt value container. More explicitly naming the container for selectively disclosable claims might be good too.

**Comment by selfissued** [comment]
I agree that using different claim names should be used when their purpose is different.

**Comment by peppelinux** [comment]
@Sakurann isn't it be closed thanks to https://github.com/oauthstuff/draft-selective-disclosure-jwt/pull/42?

**Comment by danielfett** [comment]
Fixed in #42 indeed.
