### ISSUE TITLE
SVC with JSON string values containing escaped JSON 

### ISSUE THREAD

**Issue by Sakurann** [oauthstuff/draft-selective-disclosure-jwt#27]
Comment from @b---c. 

> I understand (I think) why it's this way (per https://www.ietf.org/archive/id/draft-fett-oauth-selective-disclosure-jwt-00.html#section-4.1.1.1-3) but I really dislike the ascetics of the SVC with JSON string values containing escaped JSON https://www.ietf.org/archive/id/draft-fett-oauth-selective-disclosure-jwt-00.html#name-example-1-svc-for-a-flat-sd - at first glance I thought the examples had to be a mistake.

**Comment by Sakurann** [comment]
Should it be
```
"given_name": {
          "salt": "6Ij7tM-a5iVPGboS5tmvVA",
          "value": "John"
     }
```
instead of?
```
"given_name": "[\"6Ij7tM-a5iVPGboS5tmvVA\", \"John\"]"
```

**Comment by selfissued** [comment]
I agree that we should not use escaped JSON.

**Comment by danielfett** [comment]
> > Should it be
> > ```
> > "given_name": {
> >           "salt": "6Ij7tM-a5iVPGboS5tmvVA",
> >           "value": "John"
> >      }
> > ```
> 
> That's what I suggested [here](https://github.com/christianpaquin/selective-disclosure), although I used smaller "s" and "v" property name trying to keep the payload small.

The proposed JSON encoding in the current draft avoids normalization issues, as already mentioned by others. Just sending the value as shown here does not always work, e.g. for values that are an array and therefore have an infinite number of different representations with different hashes. There's a metric ton of other issues, e.g. around numbers that we really don't want to get into. We need to send the representation that will be hashed, not the value.

**Comment by danielfett** [comment]
See [here](https://datatracker.ietf.org/doc/html/rfc8785#section-3.2) for more examples on why canonicalization is needed:

>   Assume the following JSON object is parsed:
> 
>      {
>        "numbers": [333333333.33333329, 1E30, 4.50,
>                    2e-3, 0.000000000000000000000000001],
>        "string": "\u20ac$\u000F\u000aA'\u0042\u0022\u005c\\\"\/",
>        "literals": [null, true, false]
>      }
> 
>    If the parsed data is subsequently serialized using a serializer
>    compliant with ECMAScript's "JSON.stringify()", the result would
>    (with a line wrap added for display purposes only) be rather
>    divergent with respect to the original data:
> 
>      {"numbers":[333333333.3333333,1e+30,4.5,0.002,1e-27],"string":
>      "€$\u000f\nA'B\"\\\\\"/","literals":[null,true,false]}
> 
>    The reason for the difference between the parsed data and its
>    serialized counterpart is due to a wide tolerance on input data (as
>    defined by JSON [[RFC8259](https://datatracker.ietf.org/doc/html/rfc8259)]), while output data (as defined by
>    ECMAScript) has a fixed representation.  As can be seen in the
>    example, numbers are subject to rounding as well.

**Comment by peppelinux** [comment]
mhh ... in the JWT world any issuer can put strange bytes in a value and in "this perfect world" this should be escaped as well, we don't have c18n and it seems that everything is fine. I'd fill this gap usign a normative json-schema in the specs (annex?)

**Comment by peppelinux** [comment]
Also [this issue](https://github.com/oauthstuff/draft-selective-disclosure-jwt/issues/80) is asks for 

1. remove JSON Object in the form escaped strings (no more JSON Objects)
2. using pure JSON Objects with explicit attributes/properties

**Comment by danielfett** [comment]
> mhh ... in the JWT world any issuer can put strange bytes in a value and in "this perfect world" this should be escaped as well, we don't have c18n and it seems that everything is fine. I'd fill this gap usign a normative json-schema in the specs (annex?)

But in the JWT world, you get the thing that is signed delivered. There's no need to reconstruct it, therefore no need for c18n. 

A JSON schema does not help, because this is about the serialization, not the contents of the JSON.

How would you solve the c18n problem described above, e.g., around floating point numbers, with plain JSON objects?

**Comment by peppelinux** [comment]
a JSON Schema can define the content of the values of any attribute. 
It can restrict a value to be an integer or a string with a maxmimum length, it can also define the property of a complex type, like a nested JSON Object

**Comment by danielfett** [comment]
But how can a JSON schema prevent that *the same string* is represented using different bytes? Any validation in JSON schema is defined over the string value, not the bytes representing the string.

For arrays, you'll have the same problem.

These two will hash to different digests, but always either both be accepted by a JSON schema, or both be rejected:

```
["a", "b"]
["a","b"]
```

**Comment by peppelinux** [comment]
@danielfett json schema validates json objects and not serialization of them in different bytes

once the signature of a JWT has been validated, a json schema can validate the structure of the artifact and all the values contained in it

so signature validation and content validation are different things

**Comment by danielfett** [comment]
Exactly, that's why I don't see how a JSON schema would solve the c18n problem.

**Comment by danielfett** [comment]
It looks like we'll be keeping this awkward-looking but well-working JSON-in-JSON, I guess? @peppelinux Can we close this from your side? (We'll add more explanation as agreed in Issue #51).
