### ISSUE TITLE
specify hash function

### ISSUE THREAD

**Issue by Sakurann** [oauthstuff/draft-selective-disclosure-jwt#29]
Comment from @b---c
> I don't think the actual hash function used is specified anywhere. That kind of thing is needed for interoperability :) But then questions about algorithm agility come up...

**Comment by Sakurann** [comment]
hash function table from my original draft is omitted in the current draft - will add.

**Comment by christianpaquin** [comment]
See #13

**Comment by Sakurann** [comment]
duplication.
