### ISSUE TITLE
Binding between SD-JWT and SD-JWT Salt/Value Container (SVC)

### ISSUE THREAD

**Issue by PieterKas** [oauthstuff/draft-selective-disclosure-jwt#31]
Section 4.3 proposes a combined format of appending the SD-JWT Salt/Value Container (SVC) to the SD-JWT. To avoid mix-ups and improve reliability it may be worth establishing an explicit binding between the SD-JWT Salt/Value Container (SVC) to the SD-JWT by, for example, adding an attribute to the SD-JWT that includes the hash of the SD-JWT Salt/Value Container (SVC). This would give the holder a way to easily verify if the two structures are associated and avoid mix-ups.

**Comment by danielfett** [comment]
Do we actually need this? I have the feeling that through the existing hashes, there is already a good binding.

**Comment by PieterKas** [comment]
I think the existing hashes could be used, but there should be some clear guidance that the verifier should correlate the hashes between the SCV and SD-JWT. 

If we make it explicit (e.g. the holder should only accept the SVC and SD-JWT pairing if all the hashes match (computed, not just string compared), it could work.

**Comment by selfissued** [comment]
As per my comments on some of the other proposals, we should mirror the simplicity of mDL's salted hash claims, and stop there.  We need to resist the temptation to make things more complicated than they need to be.

**Comment by danielfett** [comment]
I'm not convinced we need any of this. The binding by the existing hashes is already quite strong. 

We can define that the holder checks that (a) the structure in the SVC actually matches the one in the SD-JWT and that (b) the holder checks that the hashes match. That's really all we need.

**Comment by PieterKas** [comment]
Agreed, that would achieve the same result. Some proposed text:

The SVC and SD-JWT are implicitly linked through the hash values of the claims in the SVC that is included in the SD-JWT. To ensure that the correct SVC and SD-JWT pairings are being used, the holder should verify that all the claims in the SVC are present in the SD-JWT, that there are no claims in the SD-JWT that are not in the SVC and that the hashes of the claims in the SVC match those in the SD-JWT.

**Comment by Sakurann** [comment]
agreed, refactored the PR #34.
