### ISSUE TITLE
Rename sd_claims to _sd_claims

### ISSUE THREAD

**Issue by selfissued** [oauthstuff/draft-selective-disclosure-jwt#4]
In OpenID Connect, we use the convention that meta claim names (claims about sets of claims) are prefixed by an underscore.  For example, see the `_claim_names` and `_claim_sources` claims defined at https://openid.net/specs/openid-connect-core-1_0.html#AggregatedDistributedClaims.  I think we should do the same.

Please rename `sd_claims` to `_sd_claims`.

**Comment by danielfett** [comment]
Thanks, I renamed `sd_claims` to just `_sd`.
