### ISSUE TITLE
Editorial issues and typos

### ISSUE THREAD

**Issue by Macke** [oauthstuff/draft-selective-disclosure-jwt#68]
Section 1 - The note at end of  is not clear

Section 2.7 - "An entity that **entity that** requests,"

Section 3.3 - Verifying an **SD-JWWT** Release

Section 4.1.1.1 - Reference to eKYC should probably be OIDC4IDA

Section 4.3 - "...base64ur-encoded..."

Section 5 - numbering format is not good from a readability perspective

**Comment by danielfett** [comment]
See PR #72. Most points in this issue have been addressed already in other commits. We can't change the list style, so keeping as is for now.
