### ISSUE TITLE
Handling claims that are in the form of a dictionary or array

### ISSUE THREAD

**Issue by nikosft** [oauthstuff/draft-selective-disclosure-jwt#73]
IMHO if a claim is in the form of a dictionary, then each element of the dictionary should be hashed separately. For example, in [Example 1](https://www.ietf.org/archive/id/draft-fett-oauth-selective-disclosure-jwt-01.html#name-example-1-sd-jwt) there is the following claim:

```JSON
"address": {
    "street_address": "123 Main St",
    "locality": "Anytown",
    "region": "Anystate",
    "country": "US"
  }
```
which is transformed to

```
"address": "JFu99NUXPq55f6DFBZ22rMkxMNHayCrfPG0FDsqbyDs",
```

Whereas it might be more useful to be transformed into something like that:

```
"address": {
    "street_address": "HASH",
    "locality": "HASH",
    "region": "HASH",
    "country": "HASH"
  }
```
In that case users can reveal, for example, only their country.

Similarly, when a claim is in the form of an array it may make sense to encode each element of the array separately. For example:

```
"liked_movies"=["Armageddon", "Titanic"]
```
Could become something like 

```
"liked_movies"=["HASH", "HASH"]
```

**Comment by peppelinux** [comment]
Ciao,
this is a very good question and probably this is the answer: `sd_jwt -t structured`

````
Payload of the SD-JWT:
{
    "iss": "https://example.com/issuer",
    "sub_jwk": {
        "kty": "RSA",
        "n": "vHdoaUhFEzs1ZCF_qCKw28d0bzNWVSls_AHUOPDFhGIN3neRpxJPmE7KD9m5J_e0y6i0Q4uObl0O-n3G4h3rSt_9Snzuk082JgZHMdTJ2StAKX4PX_9mv0fMdUbWly93q8AzneIMJCwiP8y9uYD5wiDHd2k0P4imtpaGL9dSewbEjakCmZM3nYnHBD5vHAJDrK2Ebr0M_eQOeKvFnzrHUopETrSSsNt4etnLbIaoArVBfsVIpMV7NrRox8PvMxlCy_JESxwfMcdmo0wLq_rv3N1ronsaY-RJ8lTSP5eCwGfXAdT5RnZz8xladGKZ6vLkGzsT5ZCjR3QGseTfvHy3IQ",
        "e": "AQAB"
    },
    "iat": 1656013213,
    "exp": 1656014113,
    "sd_digests": {
        "sub": "z4xgEco94diTaSruISPiE7o_wtmcOfnH_8R7X9Pa578",
        "given_name": "PvU7cWjuHUq6w-i9XFpQZhjT-uprQL3GH3mKsAJl0e0",
        "family_name": "H-Relr4cEBMlenyK1gvyx16QVpnt4MEclT5tP0aTLFU",
        "email": "ET2A1JQLF85ZpBulh6UFstGrSfR4B3KM-bjQVllhxqY",
        "phone_number": "SJnciB2DIRVA5cXBrdKoH6n45788mZyUn2rnv74uMVU",
        "address": {
            "street_address": "O7_Isd6CmZqcSobPVpMgmJwB41hPUHHG8jg5LJ8YzfY",
            "locality": "w-zTF6ljkQLTvVyp_JNyD3t5Waj-B2vb0AXH1q8OsjI",
            "region": "nTvoKpGA6YQwEZipVBIM4WVH9KWEnwiqsRjEhrxhQz4",
            "country": "u-O1yDQqDTTqOgUBSjWilgkMLzg_QOTELMfZrRT5e6k"
        },
        "birthdate": "TipyoxD43PZJF8ZEmKPrbxMElpFX_M7aBLkUpC-W53o"
    },
    "hash_alg": "sha-256"
}
````

@daniel anyway in the current implementation, usign a `complex` structure, I see this 
`"address": "[\"M0Jb57t41ubrkSuyrDT3xA\", {\"locality\": \"Maxstadt\", \"postal_code\": \"12344\", \"country\": \"DE\", \"street_address\": \"An der Weide 22\"}]"`

is it a bug of the walker implementation?

**Comment by danielfett** [comment]
Hi Nikos,

Examples 1 and 2 show exactly the two options from your comment. It is up to the issuer to decide whether to make the full address releasable as one value or to make each of the sub-claims releasable.

We don't have an example for arrays yet, but I imagine that what you are showing should be possible as well.

@peppelinux The complex example seems correct to me - what am I missing?

**Comment by nikosft** [comment]
> Hi Nikos,
> 
> Examples 1 and 2 show exactly the two options from your comment. It is up to the issuer to decide whether to make the full address releasable as one value or to make each of the sub-claims releasable.
> 
> We don't have an example for arrays yet, but I imagine that what you are showing should be possible as well.
> 
> @peppelinux The complex example seems correct to me - what am I missing?

I missed the Appendix section :) My fault.

**Comment by peppelinux** [comment]
@danielfett I was wondering if instead of a single hash for an entire JSON Object we should have, there, a JSON Object with the key:hashes for each address attribute

**Comment by danielfett** [comment]
@peppelinux Ah, now I see what you mean. In the complex example, address is intentionally a single claim. This is defined by `CLAIMS_STRUCTURE` in `complex_structured.py`. The example shows that the issuer doesn't have to descent into all subclaims and treating address as in the simple example can be a valid choice.
