### ISSUE TITLE
Github page content

### ISSUE THREAD

**Issue by peppelinux** [oauthstuff/draft-selective-disclosure-jwt#75]
Github page should publish the content of main.md and not the README of the project.
do you agree?

**Comment by danielfett** [comment]
I'd like to keep it as is. The readme provides guidance and instructions to compile everything, this would be hidden away otherwise. We can make create a more prominent link to main.md though.

**Comment by peppelinux** [comment]
It make sense, ok for the README, the important document is anyway the main.md, a link directly in the README woud be a very good strategy

**Comment by peppelinux** [comment]
indeed @Sakurann

I was refer to a preview of the last version built in the main branch and not to the official spec. I may have misunderstood, just to tell you what I mean as continuous deployment in github pages

**Comment by Sakurann** [comment]
PR #105 and #97
